/* 
 * @authors Casey Carr and Mun Young
 * Class that represents one entry (key-value pair) in a map
 * Everything in this class (except the instance variables and toString method) was
 * gloriously auto-generated by Eclipse.
 * 
 */
public class Entry<K extends Comparable<K>, V> implements Comparable<Entry<K, V>> {
	private K key;
	private V value;

	public K getKey() {
		return key;
	}
	
	public void setKey(K key) {
		this.key = key;
	}
	
	public V getValue() {
		return value;
	}
	
	public void setValue(V value) {
		this.value = value;
	}
	
	public Entry(K key, V value) {
		super();
		this.key = key;
		this.value = value;
	}
	
	public String toString() {
		return "<" + key + ", " + value + ">";
	}

	public int compareTo(Entry<K, V> o) {
		if (this.getKey().compareTo(o.getKey()) < 0)
			return -1;
		else if (this.getKey().compareTo(o.getKey()) > 0)
			return 1;
		else 
			return 0;
		
	}
}
